//! libsecret backend for GNOME Keyring/KDE Wallet integration
//!
//! This module implements credential storage using the Secret Service API.
//!
//! It talks to the Secret Service **in process** via the [`oo7`] crate
//! (`oo7::dbus::Service`), so no `secret-tool` binary or bundled libsecret C
//! library is required.
//!
//! The whole module is `#[cfg(not(target_os = "macos"))]` (gated at the `mod`
//! declaration in `secret/mod.rs`): macOS uses `MacOsKeychainBackend` and never
//! compiles `oo7`, so `LibSecretBackend` does not exist on macOS at all (R10.1,
//! R10.2).

use std::collections::HashMap;

use async_trait::async_trait;
use secrecy::SecretString;

use super::backend::{BackendAvailability, SecretBackend};
use crate::error::{SecretError, SecretResult};
use crate::models::Credentials;

/// libsecret backend for GNOME Keyring/KDE Wallet
///
/// Uses the in-process [`oo7`] Secret Service client. It works with GNOME
/// Keyring, KDE Wallet, and other Secret Service implementations.
pub struct LibSecretBackend {
    /// Application identifier for stored secrets
    application_id: String,
}

impl LibSecretBackend {
    /// Creates a new libsecret backend
    ///
    /// # Arguments
    /// * `application_id` - Application identifier for stored secrets
    ///
    /// # Returns
    /// A new `LibSecretBackend` instance
    #[must_use]
    pub fn new(application_id: impl Into<String>) -> Self {
        Self {
            application_id: application_id.into(),
        }
    }

    /// Creates a new libsecret backend with default application ID
    #[must_use]
    pub fn default_app() -> Self {
        Self::new("rustconn")
    }

    /// Builds the human-readable Secret Service item label for a lookup key.
    ///
    /// The label is a pure `/`-separated path such as
    /// `RustConn/oracle/admin (ssh)`. A `:` separator was used until 0.19.19
    /// (`RustConn: oracle/admin (ssh)`), which KDE Wallet cannot map onto a
    /// folder hierarchy — kwalletd then omits the item from its item list
    /// entirely, so RustConn entries were only visible in Seahorse
    /// (issue #264). Keys generated by
    /// `CredentialResolver::generate_keyring_key_with_hierarchy` already carry
    /// the `RustConn/` prefix; legacy flat keys and UUID keys do not, so the
    /// prefix is added when missing.
    ///
    /// The label is cosmetic — lookups match on the attribute map from
    /// [`Self::build_attributes`], never on the label — so relabelling never
    /// orphans an existing item. Items written by an older release keep their
    /// old label until the credential is stored again.
    #[must_use]
    pub fn item_label(connection_id: &str) -> String {
        if connection_id.starts_with("RustConn/") {
            connection_id.to_string()
        } else {
            format!("RustConn/{connection_id}")
        }
    }

    /// Builds the attribute map used to identify a stored secret.
    ///
    /// The map preserves the attribute scheme used by earlier `secret-tool`
    /// releases so entries stay mutually findable (backward compatibility,
    /// R11.1/R11.3): `application`, `connection_id`, and `key` (one of
    /// `username` / `password` / `key_passphrase` / `domain`).
    fn build_attributes(&self, connection_id: &str, key: &str) -> HashMap<String, String> {
        let mut attrs = HashMap::new();
        attrs.insert("application".to_string(), self.application_id.clone());
        attrs.insert("connection_id".to_string(), connection_id.to_string());
        attrs.insert("key".to_string(), key.to_string());
        attrs
    }

    /// Stores a single field value as a Secret Service item, on an open collection.
    ///
    /// Uses `replace = true` so re-saving a connection overwrites the previous
    /// item that matches the same attributes, and `window_id = None` since this
    /// backend runs headless in `rustconn-core` (no GUI handle).
    ///
    /// Takes the collection rather than opening one: see [`Self::open_collection`]
    /// for why that distinction is worth a parameter.
    async fn store_value(
        &self,
        collection: &oo7::dbus::Collection,
        connection_id: &str,
        key: &str,
        value: &str,
        label: &str,
    ) -> SecretResult<()> {
        let attrs = self.build_attributes(connection_id, key);

        // `Secret::text` stores the raw UTF-8 string with a `text/plain` content
        // type so values round-trip byte-for-byte like the old secret-tool path.
        collection
            .create_item(label, &attrs, oo7::Secret::text(value), true, None)
            .await
            .map_err(super::keyring::map_oo7_store_error)?;

        Ok(())
    }

    /// Retrieves a single field value from the Secret Service, on an open collection.
    async fn retrieve_value(
        &self,
        collection: &oo7::dbus::Collection,
        connection_id: &str,
        key: &str,
    ) -> SecretResult<Option<String>> {
        let attrs = self.build_attributes(connection_id, key);

        let items = collection
            .search_items(&attrs)
            .await
            .map_err(super::keyring::map_oo7_retrieve_error)?;

        let Some(item) = items.into_iter().next() else {
            // No matching item is not an error, just an absent value.
            return Ok(None);
        };

        let secret = item
            .secret()
            .await
            .map_err(super::keyring::map_oo7_retrieve_error)?;

        // Values were written as UTF-8 text; decode them back the same way. The
        // intermediate copy holds secret material, so it is wiped on drop and the
        // malformed-input buffer is wiped explicitly, matching `keyring::lookup`
        // and the macOS path.
        let bytes = zeroize::Zeroizing::new(secret.as_bytes().to_vec());
        let value = match String::from_utf8(bytes.to_vec()) {
            Ok(value) => value,
            Err(e) => {
                drop(zeroize::Zeroizing::new(e.into_bytes()));
                return Err(SecretError::RetrieveFailed(
                    "stored secret was not valid UTF-8".to_string(),
                ));
            }
        };

        if value.is_empty() {
            Ok(None)
        } else {
            Ok(Some(value))
        }
    }

    /// Deletes every Secret Service item matching a single field, on an open collection.
    async fn delete_value(
        &self,
        collection: &oo7::dbus::Collection,
        connection_id: &str,
        key: &str,
    ) -> SecretResult<()> {
        let attrs = self.build_attributes(connection_id, key);

        let items = collection
            .search_items(&attrs)
            .await
            .map_err(super::keyring::map_oo7_retrieve_error)?;

        for item in items {
            item.delete(None)
                .await
                .map_err(super::keyring::map_oo7_delete_error)?;
        }

        Ok(())
    }

    /// Opens the default collection on an already-connected service.
    ///
    /// Paired with [`Self::connect`]: every operation calls both once and then
    /// passes the collection down to the per-field helpers. Each field used to
    /// open its own connection instead, and `Service::new()` performs a DH
    /// handshake ("Starting an encrypted Secret Service session", ~12 ms) — so
    /// one `retrieve` cost five of them, the availability probe plus one per
    /// field, and a single credential resolution, which tries five different
    /// lookup keys, opened 25 sessions in ~330 ms. Once per operation makes that
    /// one, and the probe is cached (see [`Self::availability_probe`]).
    async fn open_collection(service: &oo7::dbus::Service) -> SecretResult<oo7::dbus::Collection> {
        service
            .default_collection()
            .await
            .map_err(super::keyring::map_oo7_service_error)
    }

    /// Connects to the Secret Service.
    async fn connect() -> SecretResult<oo7::dbus::Service> {
        oo7::dbus::Service::new()
            .await
            .map_err(super::keyring::map_oo7_service_error)
    }

    /// Probes availability via oo7's typed `Service::new()` result.
    ///
    /// A successful connection means a Secret Service answered (`Available`);
    /// any error means no service responded (`ServiceUnavailable`).
    ///
    /// The `ClientMissing` classification is intentionally never produced here:
    /// with the in-process oo7 client there is no external `secret-tool` binary
    /// that could be absent, so the only two observable outcomes are "a service
    /// answered" and "none did". oo7 does not cleanly distinguish "no session
    /// bus at all" from other transport failures (all surface as
    /// `Error::ZBus`/`Error::IO`), so collapsing every error to
    /// `ServiceUnavailable` is both correct and the least-code option.
    ///
    /// The result is cached for [`AVAILABILITY_TTL`]. `SecretManager::retrieve`
    /// probes every backend before every lookup, and a credential resolution
    /// makes five lookups, so an uncached probe was five DH handshakes on its own
    /// — for an answer that cannot meaningfully change inside one resolution. A
    /// keyring that disappears mid-TTL simply fails the lookup, which the backend
    /// chain already absorbs by moving to the next backend.
    async fn availability_probe(&self) -> BackendAvailability {
        if let Some(cached) = cached_availability() {
            return cached;
        }
        let availability = match oo7::dbus::Service::new().await {
            Ok(_) => BackendAvailability::Available,
            Err(_) => BackendAvailability::ServiceUnavailable,
        };
        cache_availability(availability.clone());
        availability
    }
}

/// How long a Secret Service availability probe is trusted.
///
/// Matches the window `AppState` already uses for its own backend-availability
/// cache. Long enough to cover one credential resolution end to end, short
/// enough that a keyring started after RustConn is picked up promptly.
const AVAILABILITY_TTL: std::time::Duration = std::time::Duration::from_secs(5);

/// Last availability answer and when it was taken.
static AVAILABILITY_CACHE: std::sync::RwLock<Option<(std::time::Instant, BackendAvailability)>> =
    std::sync::RwLock::new(None);

/// Returns the cached availability if it is still within [`AVAILABILITY_TTL`].
///
/// Borrows through the guard and clones the answer rather than moving it out:
/// `BackendAvailability` is deliberately not `Copy`, and making it `Copy` to
/// save this clone would turn every existing `.clone()` on it elsewhere into a
/// `clippy::clone_on_copy` warning.
fn cached_availability() -> Option<BackendAvailability> {
    let guard = AVAILABILITY_CACHE.read().ok()?;
    let (taken_at, availability) = guard.as_ref()?;
    let fresh = (taken_at.elapsed() < AVAILABILITY_TTL).then(|| availability.clone());
    drop(guard);
    fresh
}

/// Records an availability answer for the next [`AVAILABILITY_TTL`].
fn cache_availability(availability: BackendAvailability) {
    if let Ok(mut guard) = AVAILABILITY_CACHE.write() {
        *guard = Some((std::time::Instant::now(), availability));
    }
}

#[async_trait]
impl SecretBackend for LibSecretBackend {
    async fn store(&self, connection_id: &str, credentials: &Credentials) -> SecretResult<()> {
        let label = Self::item_label(connection_id);

        // One session for all four fields — see `open_collection`.
        let service = Self::connect().await?;
        let collection = Self::open_collection(&service).await?;

        // Store username if present
        if let Some(username) = &credentials.username {
            self.store_value(&collection, connection_id, "username", username, &label)
                .await?;
        }

        // Store password if present
        if let Some(password) = credentials.expose_password() {
            self.store_value(&collection, connection_id, "password", password, &label)
                .await?;
        }

        // Store key passphrase if present
        if let Some(passphrase) = credentials.expose_key_passphrase() {
            self.store_value(
                &collection,
                connection_id,
                "key_passphrase",
                passphrase,
                &label,
            )
            .await?;
        }

        // Store domain if present
        if let Some(domain) = &credentials.domain {
            self.store_value(&collection, connection_id, "domain", domain, &label)
                .await?;
        }

        Ok(())
    }

    async fn retrieve(&self, connection_id: &str) -> SecretResult<Option<Credentials>> {
        // One session for all four fields — see `open_collection`.
        let service = Self::connect().await?;
        let collection = Self::open_collection(&service).await?;

        // Non-secret fields first, then the secret ones. Each secret is wrapped
        // in `SecretString` on the same line it is retrieved, so no plain
        // `String` holding secret material stays alive across a later fallible
        // `?` await (where it would drop un-wiped).
        let username = self
            .retrieve_value(&collection, connection_id, "username")
            .await?;
        let domain = self
            .retrieve_value(&collection, connection_id, "domain")
            .await?;
        let password = self
            .retrieve_value(&collection, connection_id, "password")
            .await?
            .map(SecretString::from);
        let key_passphrase = self
            .retrieve_value(&collection, connection_id, "key_passphrase")
            .await?
            .map(SecretString::from);

        // If nothing was found, return None
        if username.is_none() && password.is_none() && key_passphrase.is_none() && domain.is_none()
        {
            return Ok(None);
        }

        Ok(Some(Credentials {
            username,
            password,
            key_passphrase,
            domain,
        }))
    }

    async fn delete(&self, connection_id: &str) -> SecretResult<()> {
        // One session for all four fields — see `open_collection`.
        let service = Self::connect().await?;
        let collection = Self::open_collection(&service).await?;

        // Delete all stored values for this connection
        // Ignore errors for individual keys (they might not exist)
        let _ = self
            .delete_value(&collection, connection_id, "username")
            .await;
        let _ = self
            .delete_value(&collection, connection_id, "password")
            .await;
        let _ = self
            .delete_value(&collection, connection_id, "key_passphrase")
            .await;
        let _ = self
            .delete_value(&collection, connection_id, "domain")
            .await;

        Ok(())
    }

    async fn is_available(&self) -> bool {
        self.availability().await == BackendAvailability::Available
    }

    async fn availability(&self) -> BackendAvailability {
        self.availability_probe().await
    }

    fn backend_id(&self) -> &'static str {
        "libsecret"
    }

    fn display_name(&self) -> &'static str {
        "GNOME Keyring / KDE Wallet"
    }
}

impl std::fmt::Debug for LibSecretBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LibSecretBackend")
            .field("application_id", &self.application_id)
            .finish()
    }
}

#[cfg(test)]
mod label_tests {
    use super::*;

    #[test]
    fn label_keeps_hierarchical_key_as_a_pure_path() {
        // Keys from generate_keyring_key_with_hierarchy already start with
        // "RustConn/" and must be used verbatim.
        assert_eq!(
            LibSecretBackend::item_label("RustConn/oracle/admin (ssh)"),
            "RustConn/oracle/admin (ssh)"
        );
    }

    #[test]
    fn label_prefixes_legacy_flat_key() {
        assert_eq!(
            LibSecretBackend::item_label("admin (ssh)"),
            "RustConn/admin (ssh)"
        );
    }

    #[test]
    fn label_never_uses_a_colon_separator() {
        // A ":" separator keeps kwalletd from listing the item (issue #264).
        for key in [
            "RustConn/oracle/admin (ssh)",
            "admin (ssh)",
            "550e8400-e29b-41d4-a716-446655440000",
        ] {
            let label = LibSecretBackend::item_label(key);
            assert!(
                !label.contains(':'),
                "label {label:?} must not contain a colon"
            );
            assert!(
                label.starts_with("RustConn/"),
                "label {label:?} must be a path"
            );
        }
    }
}

#[cfg(test)]
mod debug_tests {
    use super::*;

    #[test]
    fn debug_does_not_leak_secret() {
        // LibSecretBackend stores no secrets in-process; the test guards
        // against accidental future fields that could leak.
        let backend = LibSecretBackend::new("hunter2-app-id");
        let rendered = format!("{backend:?}");
        // application_id is intentionally non-secret, so it may appear.
        // Make sure we never grow a field that contains a real password.
        assert!(rendered.contains("LibSecretBackend"));
        assert!(rendered.contains("application_id"));
    }
}
