#!/bin/bash
# Regenerate rustconn.pot from source files
#
# Usage: ./po/update-pot.sh [output.pot]
#
# With no argument the canonical template `po/rustconn.pot` is rewritten in
# place. An explicit path writes there instead and leaves the committed template
# alone — which is how `scripts/check-pot-current.sh` extracts a throwaway copy
# to compare against. That gate exists so the template cannot drift out of step
# with the sources, and it deliberately calls THIS script rather than repeating
# the xgettext invocation: a second copy of the keyword list is how a string
# ends up extracted by one and missed by the other, which is the failure the
# gate is there to catch.
#
# Requires: xgettext (from gettext package)
# Install: sudo apt install gettext

set -e

DOMAIN="rustconn"
POTFILE="${1:-po/${DOMAIN}.pot}"
VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')

echo "Extracting translatable strings for ${DOMAIN} v${VERSION}..."

# Extract from Rust source files (gettext/ngettext calls via gettextrs)
# Use --language=C because xgettext doesn't natively support Rust,
# but the gettext("...") call syntax is identical to C.
#
# `LC_ALL=C sort` and not a bare `sort`: xgettext emits entries in the order it
# first meets them, so the file list decides the layout of the template, and a
# bare `sort` collates by locale. Under en_US.UTF-8 punctuation is weighted down
# and `dialogs/connection_wizard/…` sorts before `dialogs/connection/…`; under
# C.UTF-8 the byte order puts `/` (0x2F) before `_` (0x5F) and the two swap. So
# the same sources produced two different templates depending on whose shell ran
# this, with identical msgids in a different order — invisible while the file was
# only ever regenerated by hand, and fatal to `check-pot-current.sh`, which has
# to be able to tell a real drift from the machine it runs on.
xgettext \
    --language=C \
    --from-code=UTF-8 \
    --keyword=gettext \
    --keyword=ngettext:1,2 \
    --keyword=pgettext:1c,2 \
    --keyword=npgettext:1c,2,3 \
    --keyword=i18n \
    --keyword=i18n_f \
    --keyword=ni18n:1,2 \
    --keyword=ni18n_f:1,2 \
    --add-comments=Translators \
    --package-name="${DOMAIN}" \
    --package-version="${VERSION}" \
    --msgid-bugs-address="https://github.com/totoshko88/RustConn/issues" \
    --copyright-holder="Anton Isaiev" \
    --output="${POTFILE}" \
    $(find rustconn/src -name '*.rs' -type f | LC_ALL=C sort)

# Extract from desktop file and merge
xgettext \
    --from-code=UTF-8 \
    --join-existing \
    --package-name="${DOMAIN}" \
    --package-version="${VERSION}" \
    --output="${POTFILE}" \
    rustconn/assets/io.github.totoshko88.RustConn.desktop

# Extract from metainfo XML (AppStream)
if command -v itstool &> /dev/null; then
    itstool -i /usr/share/its/appdata.its -o "${POTFILE}" \
        rustconn/assets/io.github.totoshko88.RustConn.metainfo.xml 2>/dev/null || true
fi

echo "Generated ${POTFILE}"
echo "Strings: $(grep -c '^msgid ' "${POTFILE}") entries"

# Fix false c-format flag on command palette search string.
# xgettext --language=C misinterprets "% tabs" as a C format specifier.
# See CHANGELOG 0.12.6 for details.
#
# In awk rather than `sed -i`, because there is no portable spelling of that
# command: GNU takes the suffix as an optional argument glued to the flag, BSD
# takes it as a separate one, so `sed -i 'script' file` makes BSD read the
# script as the backup suffix and the filename as the script — then wait on
# stdin. The multi-line `N` + `\n` form this replaced is the other half of the
# problem, since BSD sed does not accept `\n` in a substitution the way GNU
# does. macOS ships BSD sed, so this step aborted the script on the
# maintainer's own platform, after the template had already been written: the
# POT came out carrying the spurious flag and the run exited non-zero.
awk '
  /^#, c-format$/ {
    flag = $0
    if ((getline line) <= 0) { print flag; next }
    # Drop the flag only when it decorates this one msgid; every other
    # c-format entry is genuine and must survive.
    if (line !~ /Search connections, > commands, @ tags, # groups, % tabs/) print flag
    print line
    next
  }
  { print }
' "${POTFILE}" > "${POTFILE}.tmp" && mv "${POTFILE}.tmp" "${POTFILE}"
